"""`miniai` is an unofficial machine learning library developed in part 2 of [fastai course](https://course.fast.ai/Lessons/part2.html). From that, we create `microai`."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_microai.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../nbs/00_microai.ipynb 3
def foo(): pass

# %% ../nbs/00_microai.ipynb 4
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
