"""Performing bounding box detection on PASCAL VOC 2007 using Darknet"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/52_detection.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/52_detection.ipynb 3
from minai import *

import torch
import torch.nn as nn
from torch import tensor
from torch.utils.data import DataLoader
import torch.nn.functional as F

import torchvision.transforms.v2.functional as TF
import torchvision.transforms as transforms
import torchvision.datasets as datasets
from torchvision.transforms import v2

from torcheval.metrics import MulticlassAccuracy

import fastcore.all as fc
from fastcore.utils import L
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd

from datasets import load_dataset, load_dataset_builder

from IPython.display import display, Image

from .core import *
from .darknet import *
from .pascal_class import *
